import './Create Test Data/Add_user_data.cy'
import './Login/Login.cy'
import './Reset password/Reset_password.cy'
import './Forget password/Forget_password.cy'
import './Edit profile/Edit_profile.cy'
import './Accounting/Accounting.cy'
import './User management/Add_user.cy'
import './User management/Edit_user.cy'
import './User management/User_management.cy'